version: '3.8'

services:
  calculator:
    image: monkeydmagnas007/calulator:v10.0.1
    container_name: calculator_app
    ports:
      - "80:80" # Change 80 to the correct container port if needed
    restart: always
